#!/bin/sh
commands(){
    for command in $@;
    do
        if [ ! -f "/usr/local/bin/$command" ]; then
            echo "$command not found"
            exit 1
        fi
    done
}

# Install memcached need dependent libmemcached-dev and cyrus-sasl-dev
# 5.6~ 2.1.0
# 7.~ 3.x
memcached(){
    apk add --no-cache libmemcached-dev cyrus-sasl-dev
}

extensions(){
    for extension in $@;
    do
        if [[ "$extension" =~ "memcached"  ]]; then
            memcached
        fi
    
        pecl install "$extension"
    done
}

commands php pecl phpize

#extensions redis-4.0.1 memcached-2.1.0 xdebug-2.6.0
