version: "3"
services:
  php:
    image: registry.cn-hangzhou.aliyuncs.com/magein/php-5.6.35
    ports:
      - 9000:9000
    volumes:
      # 宿主机的配置需要根据自己的目录配置
      - /php.ini:/usr/local/php/lib/php.ini
      - /php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - /var/www:/var/www
      - /log/:/usr/local/php/var/log
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/magein/nginx
    ports:
      - 80:80
    volumes:
      # 宿主机的配置需要根据自己的目录配置
      # 宿主机的nginx.conf是映射到docker容器中，所以配置文件中的路径需要指向容器中的路径
      # 宿主机的文件映射到docker容器中，会自动在容器中生成对应的文件
      - /yml/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - /var/www:/var/www
      - /yml/:/usr/local/nginx/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure