FROM alpine:3.6

RUN apk add --no-cache --virtual .fetch-deps \
        autoconf \
        dpkg-dev dpkg \
        file \
        g++ \
        gcc \
        libc-dev \
        make \
        pkgconf \
        re2c \
        gnupg \
        wget