version: "3"
services:
  php:
    image: registry.cn-hangzhou.aliyuncs.com/magein/php-5.6.35
    ports:
      - 9000:9000
    volumes:
      - /yml/php.ini:/usr/local/php-5.6.35/lib/php.ini
      - /yml/php-fpm.conf:/usr/local/php-5.6.35/etc/php-fpm.conf
      - /var/www:/var/www
      - /yml/:/usr/local/php-5.6.35/var/log
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/magein/nginx
    ports:
      - 80:80
    volumes:
      - /yml/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - /var/www:/var/www
      - /yml/:/usr/local/nginx/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure